### ISSUE TITLE
您好，训练PAF时模型没有保存，另外运行infer_PAF有报错

### ISSUE THREAD

**Issue by Sp-Bro** [LinhzTT/traffic_police_gesture_pytorch#1]
您好，刚学习深度学习很多都不懂。请问训练PAF时训练好的模型是保存在哪个目下的呀？我训练时看log.txt一直都是空文件，也没有生成其他的模型文件。
另外运行infer_paf时报错：PoseNet未定义，请问应该怎么解决呢

**Comment by linhezheng19** [comment]
训练结束才能看得到log.txt里的东西，我更新了几个问题，你重新clone一次吧。模型在ckpt文件夹下，是按照固定iter数保存的，不是一直都保存。所以要等训练一段时间。等我有时间我还会看看有什么问题，你如果发现了什么问题可以改正然后给我提交一个pull request。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Sp-Bro"<notifications@github.com&gt;; 
发送时间: 2020年7月17日(星期五) 晚上9:34
收件人: "LinhzTT/traffic_police_gesture_pytorch"<traffic_police_gesture_pytorch@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [LinhzTT/traffic_police_gesture_pytorch] 您好，训练PAF时模型没有保存，另外运行infer_PAF有报错 (#1)





 
您好，刚学习深度学习很多都不懂。请问训练PAF时训练好的模型是保存在哪个目下的呀？我训练时看log.txt一直都是空文件，也没有生成其他的模型文件。
 另外运行infer_paf时报错：PoseNet未定义，请问应该怎么解决呢

**Comment by Sp-Bro** [comment]
> 训练结束才能看得到log.txt里的东西，我更新了几个问题，你重新clone一次吧。模型在ckpt文件夹下，是按照固定iter数保存的，不是一直都保存。所以要等训练一段时间。等我有时间我还会看看有什么问题，你如果发现了什么问题可以改正然后给我提交一个pull request。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Sp-Bro"<notifications@github.com&gt;; 发送时间: 2020年7月17日(星期五) 晚上9:34 收件人: "LinhzTT/traffic_police_gesture_pytorch"<traffic_police_gesture_pytorch@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [LinhzTT/traffic_police_gesture_pytorch] 您好，训练PAF时模型没有保存，另外运行infer_PAF有报错 (#1) 您好，刚学习深度学习很多都不懂。请问训练PAF时训练好的模型是保存在哪个目下的呀？我训练时看log.txt一直都是空文件，也没有生成其他的模型文件。 另外运行infer_paf时报错：PoseNet未定义，请问应该怎么解决呢 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

非常感谢，我再训练一次试试
