### ISSUE TITLE
训练RNN网络时内存不够

### ISSUE THREAD

**Issue by Sp-Bro** [LinhzTT/traffic_police_gesture_pytorch#3]
大神好，请问您在训练ＲＮＮ时有遇到内存不够吗？　我训练时报错了，我电脑是16Ｇ的内存，显卡是RTX2060s，好像是一次将所有数据集导入的原因，但是还不知道该怎么优化

RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 9296683200 bytes. Error code 12 (Cannot allocate memory)

**Comment by linhezheng19** [comment]
我刚刚clone试了一下，没有这个问题。

**Comment by Sp-Bro** [comment]
嗯嗯，其实内存和显存都不算太小，好奇怪，我再调一下试试
