### ISSUE TITLE
COCO dataset support

### ISSUE THREAD

**Issue by datasetsk** [LinhzTT/traffic_police_gesture_pytorch#4]
### POSE parameters in configs.py is with respect to AI-Challenger dataset. Any idea, what is the value of these parameters in COCO
 _C.POSE.NUM_KPTS = 14
__C.POSE.NUM_PAFS = 22  # (11 * 2)
__C.POSE.KPT_THRESH = 0.1
__C.POSE.SCALE = (512, 512)
__C.POSE.LIMBS = [[1,2], [2,3],
                  [4,5], [5,6],
                  [14,1], [14,4],
                  [7,8], [8,9],
                  [10,11], [11,12],
                  [13,14]]
__C.POSE.HEAD = [13, 14]
__C.POSE.BODY = [[1,2], [2,3],
                  [4,5], [5,6],
                  [14,1], [14,4],
                  [7,8], [8,9],
                  [10,11], [11,12]]
__C.POSE.LIMB_WIDTH = 2.5
__C.POSE.GAUSSIAN_VAR

**Comment by linhezheng19** [comment]
Please refer to COCO official annotations, I don't remember exactly.

**Comment by datasetsk** [comment]
Ok. Thanks for the simplified code. It works great. The npy dataset generation for RNN takes more time for a single video. Can you please share the generated npy dataset for Chinese Police Gesture dataset if available.

**Comment by linhezheng19** [comment]
https://drive.google.com/drive/folders/1G9t3GwQrWkhb56kUSCVxyhCu6wD4BD2w?usp=sharing

**Comment by datasetsk** [comment]
Thanks a lot
